import type { ContractName } from "./contracts";

const hash = `sha256:${"a".repeat(64)}`;
const alternateHash = `sha256:${"b".repeat(64)}`;
const createdAt = "2026-08-12T00:00:00.000Z";
const commit = "c".repeat(40);
const source = (original: string, sourceOrder = 0) => ({
  original,
  sourceOrder,
  sourceLocation: `line:${sourceOrder + 1}`,
});
const immutable = (id: string) => ({ schemaVersion: 1, id, contentHash: hash, createdAt });

const reference = {
  source: "career",
  snapshotId: "career:snapshot-1",
  fieldPath: "person.name",
  valueHash: hash,
};

export const contractSamples: Record<ContractName, Record<string, unknown>> = {
  careerSnapshot: {
    ...immutable("career:snapshot-1"),
    sourceDocumentHash: alternateHash,
    person: {
      name: source("Michael Vasandani"),
      contacts: [
        { kind: "email", value: source("michael@example.com", 1) },
        { kind: "github", value: source("https://github.com/michael", 2) },
        { kind: "linkedin", value: source("https://linkedin.com/in/michael", 3) },
      ],
    },
    experience: [
      {
        id: "experience:one",
        organization: source("Example Corp"),
        title: source("Engineer", 1),
        dates: { start: source("2025", 2), current: true },
        sourceOrder: 0,
        bullets: [{ text: source("Built dependable systems.", 3), sourceOrder: 0 }],
      },
    ],
    education: [],
    projects: [],
    skills: [],
    optionalSections: [],
  },
  githubSnapshot: {
    ...immutable("github:snapshot-1"),
    collectedAt: createdAt,
    owner: { login: "michael", numericId: "111994254" },
    repositories: [
      {
        id: "repository:portfolio",
        name: "portfolio",
        url: "https://github.com/michael/portfolio",
        visibility: "public",
        pinPosition: 1,
        topics: ["nextjs"],
        languages: ["TypeScript"],
        releases: [],
        meaningfulActivityAt: createdAt,
        evidence: [
          {
            id: "evidence:readme",
            kind: "readme",
            sourceUrl: "https://github.com/michael/portfolio/blob/main/README.md",
            contentHash: alternateHash,
          },
        ],
        fetchOutcomes: [{ endpoint: "readme", status: "success", fetchedAt: createdAt }],
      },
    ],
  },
  presentationPolicy: {
    ...immutable("presentation:policy-1"),
    policyVersion: "1.0.0",
    primaryThesis: "Engineer of dependable agentic AI systems",
    fallbackThesis: "Software and data engineer",
    publicContactKinds: ["email", "github", "linkedin"],
    projectTarget: 5,
  },
  projectSelectionState: {
    ...immutable("selection:state-1"),
    githubSnapshotId: "github:snapshot-1",
    careerSnapshotId: "career:snapshot-1",
    selected: [
      {
        repositoryId: "repository:portfolio",
        order: 0,
        score: { pin: 35, resumeMatch: 0, evidence: 20, relevance: 10, recency: 5, total: 70 },
        resumeProjectId: null,
        consecutiveLeadDays: 0,
      },
    ],
  },
  evidencePacket: {
    ...immutable("evidence:packet-1"),
    careerSnapshotId: "career:snapshot-1",
    githubSnapshotId: "github:snapshot-1",
    presentationPolicyId: "presentation:policy-1",
    references: [reference],
  },
  generatedOutput: {
    ...immutable("generated:output-1"),
    evidencePacketId: "evidence:packet-1",
    careerSnapshotId: "career:snapshot-1",
    githubSnapshotId: "github:snapshot-1",
    presentationPolicyId: "presentation:policy-1",
    provider: "provider",
    model: "model",
    generatorVersion: "1.0.0",
    promptVersion: "1.0.0",
    clauses: [
      {
        id: "clause:one",
        text: "I build dependable systems.",
        placement: "card",
        evidenceReferences: [reference],
      },
    ],
  },
  publicationManifest: {
    ...immutable("manifest:candidate-1"),
    careerSnapshotId: "career:snapshot-1",
    githubSnapshotId: "github:snapshot-1",
    presentationPolicyId: "presentation:policy-1",
    selectionStateId: "selection:state-1",
    evidencePacketId: "evidence:packet-1",
    generatedOutputId: "generated:output-1",
    codeCommit: commit,
    schemaHash: alternateHash,
    parserVersion: "1.0.0",
    generatorVersion: "1.0.0",
    promptVersion: "1.0.0",
    approvedRendererCommit: commit,
    checkerConfigurationHashes: [alternateHash],
    candidateHash: alternateHash,
    publicOutputHash: hash,
    evidenceReferences: [reference],
    transformations: [],
    renderedFields: ["person.name"],
    checkResultIds: ["check:one"],
    deploymentId: null,
    recoveryDeploymentId: null,
  },
  publicationRun: {
    ...immutable("run:one"),
    state: "queued",
    careerSnapshotId: "career:snapshot-1",
    githubSnapshotId: "github:snapshot-1",
    presentationPolicyId: "presentation:policy-1",
    presentationPolicyVersion: "1.0.0",
    codeCommit: commit,
    schemaHash: alternateHash,
    parserVersion: "1.0.0",
    generatorVersion: "1.0.0",
    promptVersion: "1.0.0",
    approvedRendererCommit: commit,
    checkerVersions: { contract: "1.0.0" },
    checkerConfigurationHashes: { contract: alternateHash },
    priorSelectionStateId: null,
    candidateHash: null,
    idempotencyKey: "run-one",
    leaseOwner: null,
    leaseExpiresAt: null,
    checkpoint: null,
  },
  deployment: {
    ...immutable("deployment:one"),
    state: "preview",
    publicationManifestId: "manifest:candidate-1",
    candidateHash: alternateHash,
    publicOutputHash: hash,
    providerDeploymentId: "provider-deployment-1",
    precedingValidDeploymentId: null,
  },
  checkResult: {
    ...immutable("check:one"),
    checker: {
      name: "contract",
      version: "1.0.0",
      configurationHash: alternateHash,
      environment: "test",
    },
    target: "manifest:candidate-1",
    startedAt: createdAt,
    finishedAt: createdAt,
    outcome: "passed",
    measurements: { assertions: 1 },
    retryHistory: [],
    artifactPointer: "artifacts/check-one.json",
  },
  outboxRecord: {
    ...immutable("outbox:one"),
    effect: "deployment",
    state: "pending",
    idempotencyKey: "deploy-one",
    aggregateId: "run:one",
    leaseExpiresAt: null,
    providerReference: null,
    attempts: 0,
  },
  breakerState: {
    ...immutable("breaker:production"),
    state: "closed",
    servedDeploymentId: "deployment:one",
    openedByDeploymentId: null,
    reason: null,
  },
  auditRecord: {
    ...immutable("audit:one"),
    event: "publication-run-created",
    actor: "system",
    aggregateId: "run:one",
    outcome: "accepted",
    details: { idempotencyKey: "run-one" },
  },
};
